/**
 * Value Proposition Report Visual
 * CONCEPT: "The Reveal"
 * Beautiful display of the AI-generated value proposition report
 */

'use client';

import React, { useEffect, useRef, useState } from 'react';
import { Button } from './';
import { cn } from '../lib/utils';

export interface AIReport {
  context: string;
  challenges: string[];
  opportunities: string[];
  valueProposition: string;
  nextSteps: string[];
}

interface ValuePropositionReportProps {
  report: AIReport;
  userName: string;
  onHomeClick: () => void;
  onContactClick: () => void;
}

export const ValuePropositionReport: React.FC<ValuePropositionReportProps> = ({
  report,
  userName,
  onHomeClick,
  onContactClick,
}) => {
  const [isVisible, setIsVisible] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) setIsVisible(true);
      },
      { threshold: 0.1 }
    );
    if (containerRef.current) observer.observe(containerRef.current);
    return () => observer.disconnect();
  }, []);

  const handleDownload = () => {
    const content = `
AI READINESS VALUE PROPOSITION REPORT
Generated for: ${userName}
Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

================================================================================

BUSINESS CONTEXT
--------------------------------------------------------------------------------
${report.context}

KEY CHALLENGES & PAIN POINTS
--------------------------------------------------------------------------------
${report.challenges.map((c, i) => `${i + 1}. ${c}`).join('\n')}

AI TRANSFORMATION OPPORTUNITIES
--------------------------------------------------------------------------------
${report.opportunities.map((o, i) => `${i + 1}. ${o}`).join('\n')}

PERSONALIZED VALUE PROPOSITION
--------------------------------------------------------------------------------
${report.valueProposition}

RECOMMENDED NEXT STEPS
--------------------------------------------------------------------------------
${report.nextSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

================================================================================
Generated by Light Brand Consulting AI Analysis
https://lightbrandconsulting.com
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AI-Value-Proposition-Report-${userName.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div
      ref={containerRef}
      className={cn(
        'transition-all duration-1000',
        isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
      )}
    >
      {/* Success Header */}
      <div className="text-center mb-10">
        {/* Success Badge */}
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-success/10 border border-success/20 rounded-full text-success text-sm font-medium mb-6">
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
          </svg>
          Analysis Complete
        </div>

        <h1 className="text-3xl md:text-4xl font-bold text-text-primary mb-4">
          Your Personalized Value Proposition
        </h1>
        <p className="text-text-secondary text-lg max-w-2xl mx-auto">
          We've analyzed your business and created a custom AI transformation report just for you.
        </p>
      </div>

      {/* Report Card */}
      <div className="relative">
        {/* Glow Background */}
        <div className="absolute -inset-4 bg-gradient-to-b from-radiance-gold/10 to-transparent blur-3xl rounded-3xl -z-10" />

        <div className="bg-depth-elevated/30 border border-radiance-gold/20 rounded-2xl overflow-hidden backdrop-blur-sm">
          {/* Report Header */}
          <div className="bg-gradient-to-r from-radiance-gold/10 to-radiance-amber/10 border-b border-radiance-gold/20 p-6 md:p-8">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div>
                <h2 className="text-xl font-bold text-text-primary mb-1">AI Readiness Report</h2>
                <p className="text-text-muted text-sm">
                  Prepared for {userName} &bull; {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                </p>
              </div>
              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-2 px-4 py-2 bg-depth-surface hover:bg-depth-elevated border border-depth-border rounded-lg text-sm text-text-secondary hover:text-text-primary transition-all duration-200"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                Download Report
              </button>
            </div>
          </div>

          {/* Report Content */}
          <div className="p-6 md:p-8 space-y-10">
            {/* Business Context */}
            <section className="opacity-0 animate-fade-in" style={{ animationDelay: '100ms', animationFillMode: 'forwards' }}>
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-blue-500/20 text-blue-400 flex items-center justify-center">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                  </svg>
                </div>
                <h3 className="text-lg font-semibold text-text-primary">Business Context</h3>
              </div>
              <p className="text-text-secondary leading-relaxed pl-13">{report.context}</p>
            </section>

            {/* Challenges */}
            <section className="opacity-0 animate-fade-in" style={{ animationDelay: '200ms', animationFillMode: 'forwards' }}>
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-orange-500/20 text-orange-400 flex items-center justify-center">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                  </svg>
                </div>
                <h3 className="text-lg font-semibold text-text-primary">Key Challenges & Pain Points</h3>
              </div>
              <ul className="space-y-3 pl-13">
                {report.challenges.map((challenge, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-orange-400 mt-2 flex-shrink-0" />
                    <span className="text-text-secondary">{challenge}</span>
                  </li>
                ))}
              </ul>
            </section>

            {/* Opportunities */}
            <section className="opacity-0 animate-fade-in" style={{ animationDelay: '300ms', animationFillMode: 'forwards' }}>
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-success/20 text-success flex items-center justify-center">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                </div>
                <h3 className="text-lg font-semibold text-text-primary">AI Transformation Opportunities</h3>
              </div>
              <ul className="space-y-3 pl-13">
                {report.opportunities.map((opportunity, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-success mt-2 flex-shrink-0" />
                    <span className="text-text-secondary">{opportunity}</span>
                  </li>
                ))}
              </ul>
            </section>

            {/* Value Proposition */}
            <section className="opacity-0 animate-fade-in" style={{ animationDelay: '400ms', animationFillMode: 'forwards' }}>
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-radiance-gold/20 text-radiance-gold flex items-center justify-center">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
                  </svg>
                </div>
                <h3 className="text-lg font-semibold text-text-primary">Personalized Value Proposition</h3>
              </div>
              <div className="pl-13 bg-depth-surface/50 border border-depth-border rounded-xl p-6">
                <p className="text-text-secondary leading-relaxed whitespace-pre-line">{report.valueProposition}</p>
              </div>
            </section>

            {/* Next Steps */}
            <section className="opacity-0 animate-fade-in" style={{ animationDelay: '500ms', animationFillMode: 'forwards' }}>
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-purple-500/20 text-purple-400 flex items-center justify-center">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
                  </svg>
                </div>
                <h3 className="text-lg font-semibold text-text-primary">Recommended Next Steps</h3>
              </div>
              <ol className="space-y-3 pl-13">
                {report.nextSteps.map((step, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <span className="w-6 h-6 rounded-full bg-purple-500/20 text-purple-400 text-xs font-semibold flex items-center justify-center flex-shrink-0">
                      {index + 1}
                    </span>
                    <span className="text-text-secondary">{step}</span>
                  </li>
                ))}
              </ol>
            </section>
          </div>

          {/* Report Footer */}
          <div className="border-t border-depth-border bg-depth-surface/30 p-6 md:p-8">
            <div className="text-center">
              <p className="text-text-secondary mb-6">
                We'll be in touch within 24 hours to discuss your personalized AI transformation roadmap.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button variant="primary" onClick={onContactClick}>
                  Schedule a Call
                </Button>
                <Button variant="ghost" onClick={onHomeClick}>
                  Back to Home
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ValuePropositionReport;
